export class CashService {
    checkValue = () => {
        console.log('가진돈을 검증합니다.');
        // 1. 가진돈을 검증하는 코드 (대략 10줄 정도)
        // ...
        // ...
        // ...
        // ...
        return true;
    }
}
