export class ProductService {
    checkSoldOut = () => {
        console.log('판매가 완료됬는지 검증합니다.')
        // 2. 판매여부를 검증하는 코드 (대략 10줄 정도)
        // ...
        // ...
        // ...
        // ...
        return false
    }
}
